### PR TITLE
[TOOLS-2125]: add Gobi Tesnet

### PR DESCRIPTION
**Pull request by rabyyuson**
### Ticket

https://horizenlabs.atlassian.net/browse/TOOLS-2125

### Preview

https://feature-tools-2125-gobi-test.evm-documentation.pages.dev/

### Changes

- Add the Gobi Testnet network details to the EON docs "Get Started" page in lieu of Yuma Testnet
- Replace mention of Yuma with Gobi throughout the documentation, and replace any RPC URLs, Chain IDs with that of Gobi

### CODE REVIEW

**Comment by yurikoinaba** [comment]
There's probably mention of `Yuma` on other pages too. Could you do a find all on the entire repo and check?

**Review by yurikoinaba — APPROVED** [review]

**Comment by rabyyuson** [comment]
Hi @voyenavion @taijonsmith @Ramone-HL @jmontesdeocanuez, what do you all think about this PR?

**Review by taijonsmith — APPROVED** [review]
Looks good!

**Comment by rabyyuson** [comment]
> Looks good!

Thanks @taijonsmith!

**Pull request merged**
