### PR TITLE
feat: add governance

### PR DESCRIPTION
**Pull request by rabyyuson**
### Ticket

- https://horizenlabs.atlassian.net/browse/TOOLS-2698

### Changes

- Rename __docs__ to __horizen_eon__

### Preview

https://feature-navbar-items.evm-documentation.pages.dev/

### CODE REVIEW

**Comment by yurikoinaba** [comment]
Looks good.
One question I have is, is it okay that the urls to the EON sections now have `/horizen_eon/` (I think bc of the new folder structure), i.e. do we have links to documentation somewhere that will no longer work bc of this?

**Comment by rabyyuson** [comment]
> Looks good. One question I have is, is it okay that the urls to the EON sections now have `/horizen_eon/` (I think bc of the new folder structure), i.e. do we have links to documentation somewhere that will no longer work bc of this?

Right, that might be the case. And I don't think we have url redirects set up to move hardcoded links to this new structure. I can most certainly revert the directory structure change and just update the navbar label to **Horizen EON** to prevent existing links from breaking.

**Comment by jmontesdeocanuez** [comment]
LGTM overall. Just a question, on the new md files for the governance docs, why some of them are pure markdown, and others are in html?

**Comment by rabyyuson** [comment]
> LGTM overall. Just a question, on the new md files for the governance docs, why some of them are pure markdown, and others are in html?

I wasn't getting the formatting that I was looking for or it was rendering differently that's why I mixed it with HTML (for example the line breaks between paragraphs or unordered lists, nested unordered lists, and tabbing to provide structure). 😅

It should be okay to mix HTML with markdown I believe https://www.markdownguide.org/basic-syntax/#html and it is mostly helpful for further customizations and control. Also I'm more used to it and it's my personal go to. 😂

**Comment by jmontesdeocanuez** [comment]
> > LGTM overall. Just a question, on the new md files for the governance docs, why some of them are pure markdown, and others are in html?
> 
> I wasn't getting the formatting that I was looking for or it was rendering differently that's why I mixed it with HTML (for example the line breaks between paragraphs or unordered lists, nested unordered lists, and tabbing to provide structure). 😅
> 
> It should be okay to mix HTML with markdown I believe https://www.markdownguide.org/basic-syntax/#html and it is mostly helpful for further customizations and control. Also I'm more used to it and it's my personal go to. 😂

No problem on my side! I was asking because if other non-technical people, like Manon, will be doing updates to these docs, if they're in HTML it could be harder. If there are just copy edits would be fine, because they'd just need to find the text they want to modify, but other things could be more complex!

**Pull request closed without merging**
