### PR TITLE
added Security for Developers

### PR DESCRIPTION
**Pull request by Ramone-HL**
EON Security for Developers

### CODE REVIEW

**Review by taijonsmith — APPROVED** [review]

**Comment by yurikoinaba** [comment]
lgtm.
You'll have to merge the latest changes from `main` and also take care of the unsigned commit

**Review by Ramone-HL — COMMENTED** [review]
lgtm

**Review by yurikoinaba — APPROVED** [review]

**Comment by Ramone-HL** [comment]
this PR has an unverified commit that cannot be mitigated. Therefore, I am closing it out.

**Comment by Ramone-HL** [comment]
This PR has a commit issue that cannot be resolved.

**Pull request closed without merging**
