### PR TITLE
Fix Broken Staking Section

### PR DESCRIPTION
**Pull request by taijonsmith**

### CODE REVIEW

**Comment by taijonsmith** [comment]
@Ramone-HL note, run `npm run build` in your console to view any potential errors

**Review by yurikoinaba — COMMENTED** [review]
I don’t see the “How to Stake on EON” page in the preview

**Review by Ramone-HL — COMMENTED** [review]
@taijonsmith yes, I ran npm run build, first then npm run start

**Comment by taijonsmith** [comment]
> @taijonsmith yes, I ran npm run build, first then npm run start

@Ramone-HL I'm talking about in general, not this specific branch. I already fixed the error here

**Comment by taijonsmith** [comment]
Staking page now shows

**Review by Ramone-HL — APPROVED** [review]

**Comment by Ramone-HL** [comment]
Looks good...nice work!

**Review by yurikoinaba — APPROVED** [review]

**Review by yurikoinaba — APPROVED** [review]

**Pull request merged**
